{% set name = "rnc2rng" %}
{% set version = "2.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/rnc2rng-{{ version }}.tar.gz
  sha256: dd9ffbbd69d09cb07e6e7a8cf80fd28703fdc6d3b9026f8756b49cbe3314676b

build:
  entry_points:
    - rnc2rng = rnc2rng.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - rply

test:
  source_files:
    - test.py
    - tests
  imports:
    - rnc2rng
  commands:
    - pip check
    - python test.py
  requires:
    - pip

about:
  home: https://github.com/djc/rnc2rng
  summary: RELAX NG Compact to regular syntax conversion library
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - maxb2
